apiVersion: apps/v1
kind: Deployment
metadata:
   name: python-app-deployment
   labels:
     app: python-deployment
spec:
   replicas: 1
   selector:
      matchLabels:
         app: devops-python-app
   template:
     metadata:
       name: flask-app
       labels:
         app: devops-python-app
     spec:
       containers:
        - name: flask-app-container
          image: soufyanebusiness/devops-python-app:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 5000